/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/edreed/azure-permissions-checker/pkg/apis/permissions/v1alpha1"
	scheme "github.com/edreed/azure-permissions-checker/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AzPermissionsGetter has a method to return a AzPermissionInterface.
// A group's client should implement this interface.
type AzPermissionsGetter interface {
	AzPermissions() AzPermissionInterface
}

// AzPermissionInterface has methods to work with AzPermission resources.
type AzPermissionInterface interface {
	Create(ctx context.Context, azPermission *v1alpha1.AzPermission, opts v1.CreateOptions) (*v1alpha1.AzPermission, error)
	Update(ctx context.Context, azPermission *v1alpha1.AzPermission, opts v1.UpdateOptions) (*v1alpha1.AzPermission, error)
	UpdateStatus(ctx context.Context, azPermission *v1alpha1.AzPermission, opts v1.UpdateOptions) (*v1alpha1.AzPermission, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AzPermission, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AzPermissionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzPermission, err error)
	AzPermissionExpansion
}

// azPermissions implements AzPermissionInterface
type azPermissions struct {
	client rest.Interface
}

// newAzPermissions returns a AzPermissions
func newAzPermissions(c *PermissionsV1alpha1Client) *azPermissions {
	return &azPermissions{
		client: c.RESTClient(),
	}
}

// Get takes name of the azPermission, and returns the corresponding azPermission object, and an error if there is any.
func (c *azPermissions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzPermission, err error) {
	result = &v1alpha1.AzPermission{}
	err = c.client.Get().
		Resource("azpermissions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AzPermissions that match those selectors.
func (c *azPermissions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzPermissionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AzPermissionList{}
	err = c.client.Get().
		Resource("azpermissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested azPermissions.
func (c *azPermissions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("azpermissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a azPermission and creates it.  Returns the server's representation of the azPermission, and an error, if there is any.
func (c *azPermissions) Create(ctx context.Context, azPermission *v1alpha1.AzPermission, opts v1.CreateOptions) (result *v1alpha1.AzPermission, err error) {
	result = &v1alpha1.AzPermission{}
	err = c.client.Post().
		Resource("azpermissions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azPermission).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a azPermission and updates it. Returns the server's representation of the azPermission, and an error, if there is any.
func (c *azPermissions) Update(ctx context.Context, azPermission *v1alpha1.AzPermission, opts v1.UpdateOptions) (result *v1alpha1.AzPermission, err error) {
	result = &v1alpha1.AzPermission{}
	err = c.client.Put().
		Resource("azpermissions").
		Name(azPermission.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azPermission).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *azPermissions) UpdateStatus(ctx context.Context, azPermission *v1alpha1.AzPermission, opts v1.UpdateOptions) (result *v1alpha1.AzPermission, err error) {
	result = &v1alpha1.AzPermission{}
	err = c.client.Put().
		Resource("azpermissions").
		Name(azPermission.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(azPermission).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the azPermission and deletes it. Returns an error if one occurs.
func (c *azPermissions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("azpermissions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *azPermissions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("azpermissions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched azPermission.
func (c *azPermissions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzPermission, err error) {
	result = &v1alpha1.AzPermission{}
	err = c.client.Patch(pt).
		Resource("azpermissions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
